# Generated by Django 4.2.10 on 2024-08-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3'),
        ),
    ]
